--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/AlexPads/CustomShopUI
branches:
- master
projects:
  CustomShopUI:
    path: ""
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
...
