Title: ShopUI
# If True the command only works when in Survival
Survival: false
messages:
  # you can use {money}, {cost], {amount}, {name}, and {item}!
  paid-for: "you bought {amount} of {item} for {cost}!"
  not-enough-money: "You tried to by {amount} of {name} for {cost} but you were missing {missing} dollars."
  money: "you have: "
  money-recieved: "you received {money}"
  not-enough-items: "you don't have {amount} of {name}"
  how-many: "How Many"
  how-many2: " would you Like?"
  thanks: "Thank you for Shoping at"
  Survival: "You Must be in Survival to run this Command!"